<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Rocket</Name>
            <StageCount>2</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>35</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>0.0</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>978.8803241824186</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>400.2470819561527</KnownMass>
                    <Density>1240.0</Density>
                    <Material>PLA</Material>
                    <Name>Nose cone</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>400.2470819561527</CalcMass>
                    <CalcCG>247.17106577828028</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>400.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>0</SerialNo>
                    <ShapeCode>3</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>3.0</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <BaseDia>102.2096</BaseDia>
                    <ShoulderLen>20.0</ShoulderLen>
                    <ShoulderOD>100.0</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>68.33992453328906</KnownMass>
                    <Density>1200.0</Density>
                    <Material>Polycarbonate (Lexan)</Material>
                    <Name>Camera Bay</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>68.33992453328906</CalcMass>
                    <CalcCG>60.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>120.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>1</SerialNo>
                    <OD>102.2096</OD>
                    <ID>99.2096</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>99.2096</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>117.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>GoPro bay</Name>
                            <KnownCG>35.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>35.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>45.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>2</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Ring>
                            <KnownMass>24.350497150756432</KnownMass>
                            <Density>630.0</Density>
                            <Material>Plywood (birch)</Material>
                            <Name>Bulkhead 1</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>25.0</Xb>
                            <CalcMass>24.350497150756432</CalcMass>
                            <CalcCG>2.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>5.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <OD>99.2096</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>100.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>GoPro bay</Name>
                            <KnownCG>32.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>32.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>53.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>4</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>233.5648597545376</KnownMass>
                    <Density>950.0</Density>
                    <Material>Kraft phenolic</Material>
                    <Name>Body tube 1</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>233.5648597545376</CalcMass>
                    <CalcCG>250.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>500.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>5</SerialNo>
                    <OD>102.2096</OD>
                    <ID>99.0996</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>99.0996</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>0.0</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Tube coupler 1</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-20.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>21.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>42.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <OD>101.00959999999999</OD>
                            <ID>101.00959999999999</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>24.296529193128876</KnownMass>
                            <Density>630.0</Density>
                            <Material>Plywood (birch)</Material>
                            <Name>Bulkhead 2</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>30.0</Xb>
                            <CalcMass>24.296529193128876</CalcMass>
                            <CalcCG>2.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>5.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>7</SerialNo>
                            <OD>99.0996</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>250.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Avionics 1</Name>
                            <KnownCG>39.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>39.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>150.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>8</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Ring>
                            <KnownMass>104.1279822562666</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Bulkhead 3</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>190.00000000000009</Xb>
                            <CalcMass>104.1279822562666</CalcMass>
                            <CalcCG>2.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>5.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <OD>99.0996</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>0.7200000000000001</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock Cord Main</Name>
                            <KnownCG>287.00000000000006</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>287.00000000000006</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>12.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>10</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Parachute>
                            <KnownMass>151.1235911895629</KnownMass>
                            <Density>0.006700000000000001</Density>
                            <Material>Ripstop nylon</Material>
                            <Name>Parachute Main</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-12.0</Xb>
                            <CalcMass>151.1235911895629</CalcMass>
                            <CalcCG>145.0</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>290.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>11</SerialNo>
                            <Dia>1676.3999999999999</Dia>
                            <ShroudLineCount>6</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>300.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0018</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Elastic cord (round 2 mm, 1/16 in)</ShroudLineMaterial>
                            <DragCoefficient>0.97</DragCoefficient>
                        </Parachute>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>172.81610963474057</KnownMass>
                    <Density>950.0</Density>
                    <Material>Kraft phenolic</Material>
                    <Name>Body tube 2</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>172.81610963474057</CalcMass>
                    <CalcCG>185.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>370.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>12</SerialNo>
                    <OD>102.2096</OD>
                    <ID>99.10000000000001</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>99.10000000000001</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>0.0</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Tube coupler 2</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>341.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>30.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>60.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>13</SerialNo>
                            <OD>99.10000000000001</OD>
                            <ID>99.10000000000001</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Parachute>
                            <KnownMass>66.0124426330353</KnownMass>
                            <Density>0.006700000000000001</Density>
                            <Material>Ripstop nylon</Material>
                            <Name>Parachute Drogue</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>218.0</Xb>
                            <CalcMass>66.0124426330353</CalcMass>
                            <CalcCG>60.0</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>120.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>14</SerialNo>
                            <Dia>1092.2</Dia>
                            <ShroudLineCount>6</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>300.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0018</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Elastic cord (round 2 mm, 1/16 in)</ShroudLineMaterial>
                            <DragCoefficient>0.97</DragCoefficient>
                        </Parachute>
                        <MassObject>
                            <KnownMass>0.7200000000000001</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock Cord Drogue</Name>
                            <KnownCG>197.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>197.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>15.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>15</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <BodyTube>
                            <KnownMass>12.053687826034468</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Upper Engine Mount</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>12.053687826034468</CalcMass>
                            <CalcCG>93.00000000000001</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>186.00000000000003</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>16</SerialNo>
                            <OD>38.4</OD>
                            <ID>38.0</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>38.0</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <Ring>
                            <KnownMass>8.259463070782502</KnownMass>
                            <Density>630.0</Density>
                            <Material>Plywood (birch)</Material>
                            <Name>Centering ring 1</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>158.0</Xb>
                            <CalcMass>8.259463070782502</CalcMass>
                            <CalcCG>1.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>2.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>17</SerialNo>
                            <OD>99.10000000000001</OD>
                            <ID>38.4</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>8.259463070782502</KnownMass>
                            <Density>630.0</Density>
                            <Material>Plywood (birch)</Material>
                            <Name>Centering ring 2</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>20.0</Xb>
                            <CalcMass>8.259463070782502</CalcMass>
                            <CalcCG>1.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>2.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>18</SerialNo>
                            <OD>99.10000000000001</OD>
                            <ID>38.4</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <CustomFinSet>
                            <KnownMass>145.1358</KnownMass>
                            <Density>1240.0</Density>
                            <Material>PLA</Material>
                            <Name>Fins Stage 2</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>145.1358</CalcMass>
                            <CalcCG>124.66666666666661</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>19</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>0.0</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>0.0</SemiSpan>
                            <SweepDistance>0.0</SweepDistance>
                            <Thickness>3.0</Thickness>
                            <ShapeCode>2</ShapeCode>
                            <TipShapeCode>2</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                            <PointList>204.0,0.0|204.0,75.0|102.0,75.0|0.0,0.0|</PointList>
                        </CustomFinSet>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts>
                <BodyTube>
                    <KnownMass>112.09693597929125</KnownMass>
                    <Density>950.0</Density>
                    <Material>Kraft phenolic</Material>
                    <Name>Body tube 3</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>112.09693597929125</CalcMass>
                    <CalcCG>120.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>240.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>20</SerialNo>
                    <OD>102.2096</OD>
                    <ID>99.10000000000001</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>99.10000000000001</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>104.12882285051647</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Bulkhead 4</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>10.999999999999996</Xb>
                            <CalcMass>104.12882285051647</CalcMass>
                            <CalcCG>2.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>5.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>21</SerialNo>
                            <OD>99.10000000000001</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>300.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Staging system</Name>
                            <KnownCG>19.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>19.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>100.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>22</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Ring>
                            <KnownMass>24.296725331787176</KnownMass>
                            <Density>630.0</Density>
                            <Material>Plywood (birch)</Material>
                            <Name>Bulkhead 5</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>110.0</Xb>
                            <CalcMass>24.296725331787176</CalcMass>
                            <CalcCG>2.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>5.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>23</SerialNo>
                            <OD>99.10000000000001</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>0.7200000000000001</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock cord 3</Name>
                            <KnownCG>140.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>140.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>19.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>24</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Parachute>
                            <KnownMass>62.0</KnownMass>
                            <Density>0.006700000000000001</Density>
                            <Material>Ripstop nylon</Material>
                            <Name>Parachute stage 1</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>160.0</Xb>
                            <CalcMass>67.03844263303532</CalcMass>
                            <CalcCG>55.00000000000002</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>110.00000000000004</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>25</SerialNo>
                            <Dia>1092.2</Dia>
                            <ShroudLineCount>6</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>711.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.001</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Braided nylon (2 mm, 1/16 in)</ShroudLineMaterial>
                            <DragCoefficient>1.5</DragCoefficient>
                        </Parachute>
                        <Ring>
                            <KnownMass>0.0</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Tube coupler 3</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-10.999999999999996</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>9.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>19.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>26</SerialNo>
                            <OD>100.0</OD>
                            <ID>100.0</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>43.66874509192626</KnownMass>
                    <Density>950.0</Density>
                    <Material>Kraft phenolic</Material>
                    <Name>Body tube 4</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>43.66874509192626</CalcMass>
                    <CalcCG>119.99999999999999</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>239.99999999999997</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>27</SerialNo>
                    <OD>102.2096</OD>
                    <ID>101.00959999999999</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>101.00959999999999</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>0.9179999999999999</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock cord 4</Name>
                            <KnownCG>30.000000000000036</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>30.000000000000036</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>15.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>28</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <BodyTube>
                            <KnownMass>21.754837975725554</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Lower Engine Mount #1</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>21.754837975725554</CalcMass>
                            <CalcCG>93.00000000000001</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>19.0</RadialLoc>
                            <RadialAngle>3.141592653589793</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>186.00000000000003</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>30</SerialNo>
                            <OD>38.0</OD>
                            <ID>34.99999999999999</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>34.99999999999999</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <BodyTube>
                            <KnownMass>21.754837975725554</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Lower Engine Mount #2</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>21.754837975725554</CalcMass>
                            <CalcCG>93.00000000000001</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>19.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>186.00000000000003</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>31</SerialNo>
                            <OD>38.0</OD>
                            <ID>34.99999999999999</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>34.99999999999999</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <Ring>
                            <KnownMass>8.667861090048982</KnownMass>
                            <Density>630.0</Density>
                            <Material>Plywood (birch)</Material>
                            <Name>Centering ring 3</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>173.00000000000003</Xb>
                            <CalcMass>8.667861090048982</CalcMass>
                            <CalcCG>1.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>2.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>32</SerialNo>
                            <OD>101.00959999999999</OD>
                            <ID>38.0</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>8.667861090048982</KnownMass>
                            <Density>630.0</Density>
                            <Material>Plywood (birch)</Material>
                            <Name>Centering ring 4</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>10.0</Xb>
                            <CalcMass>8.667861090048982</CalcMass>
                            <CalcCG>1.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>2.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>33</SerialNo>
                            <OD>101.00959999999999</OD>
                            <ID>38.0</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>0.0</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Tube coupler 4</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>210.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>30.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>60.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>34</SerialNo>
                            <OD>101.00959999999999</OD>
                            <ID>101.00959999999999</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <CustomFinSet>
                            <KnownMass>144.58499999999998</KnownMass>
                            <Density>1050.0</Density>
                            <Material>Quantum tubing</Material>
                            <Name>Fins Stage 1</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>144.58499999999998</CalcMass>
                            <CalcCG>124.66666666666661</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>35</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>0.0</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>0.0</SemiSpan>
                            <SweepDistance>0.0</SweepDistance>
                            <Thickness>3.0</Thickness>
                            <ShapeCode>2</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                            <PointList>204.0,0.0|204.0,75.0|102.0,75.0|0.0,0.0|</PointList>
                        </CustomFinSet>
                    </AttachedParts>
                </BodyTube>
            </Stage2Parts>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>